// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXqmGCQdmUmghVlKv9y0us9-eXyea_seY',
    appId: '1:904321833568:web:9e7d9b37b2caba76f2c105',
    messagingSenderId: '904321833568',
    projectId: 'flowers-ss',
    authDomain: 'flowers-ss.firebaseapp.com',
    databaseURL: 'https://flowers-ss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flowers-ss.appspot.com',
    measurementId: 'G-HHBBNKHPKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7L0VZK2EuFy9kWOXY4Wt7pCshol7uD0I',
    appId: '1:904321833568:android:66ebd315ef7b5948f2c105',
    messagingSenderId: '904321833568',
    projectId: 'flowers-ss',
    databaseURL: 'https://flowers-ss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flowers-ss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq2xK-JPZe0iSFNd97445Q2EPD1HLAQ4c',
    appId: '1:904321833568:ios:67cc5a16bb40de1ff2c105',
    messagingSenderId: '904321833568',
    projectId: 'flowers-ss',
    databaseURL: 'https://flowers-ss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flowers-ss.appspot.com',
    iosBundleId: 'com.example.flores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq2xK-JPZe0iSFNd97445Q2EPD1HLAQ4c',
    appId: '1:904321833568:ios:67cc5a16bb40de1ff2c105',
    messagingSenderId: '904321833568',
    projectId: 'flowers-ss',
    databaseURL: 'https://flowers-ss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flowers-ss.appspot.com',
    iosBundleId: 'com.example.flores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXqmGCQdmUmghVlKv9y0us9-eXyea_seY',
    appId: '1:904321833568:web:9e58abc513ecfff8f2c105',
    messagingSenderId: '904321833568',
    projectId: 'flowers-ss',
    authDomain: 'flowers-ss.firebaseapp.com',
    databaseURL: 'https://flowers-ss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flowers-ss.appspot.com',
    measurementId: 'G-VVTWMNNWQY',
  );
}
